vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: /image/blog
            upload_destination: '%kernel.project_dir%/public/image/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
